#143865383 Fix failing tests and update travis
andela/mifune-cfh pull request #16
Opened 2017-04-20 00:39 UTC by andela-onnenanya

#### What does this PR do?
Fix failing tests and update travis.yml
#### Description of Task to be completed?
Fix failing tests and update travis.yml
#### How should this be manually tested?
Run 'npm test' or open travis-ci dashboard for the branch
#### Any background context you want to provide?
N/A
#### What are the relevant pivotal tracker stories?
Fix failing tests and update travis.yml
#### Screenshots (if appropriate)
<img width="1280" alt="screen shot 2017-04-20 at 1 36 49 am" src="https://cloud.githubusercontent.com/assets/26964897/25208057/0ca39d30-256a-11e7-8678-f7e8e405e9a3.png">

![image](https://cloud.githubusercontent.com/assets/26964897/25208027/edf82040-2569-11e7-8bd7-ef29672981e5.png)
#### Questions:
N/A

2017-04-21 10:01 UTC, emmyakin requested changes

2017-04-21 10:01 UTC, andela-eakinyele commented on article.js
> +var mongoose = require('mongoose'),
this file should be written in es6 syntax

2017-04-21 10:01 UTC, andela-eakinyele commented on test/user/model.js
>          describe('Method Save', function() {
you should also write this is es6 syntax arrow functions

2017-04-25 16:31 UTC, emmyakin requested changes
make minor changes and update

2017-04-25 16:31 UTC, emmyakin commented on .eslintrc
> +      "no-console": "off",
can you remove this.
if you need to disable console.log, where needed, use // eslint-disable-line

2017-04-25 16:31 UTC, andela-eakinyele commented on test/frontend/unit/testingAngularUnitSpec.js
> +        const ctrl = $controller('HeaderController', { $scope: scope, Global: { test: 'test' } });
use // eslint-disable-line here

2017-04-25 16:31 UTC, andela-eakinyele commented on test/frontend/unit/testingAngularUnitSpec.js
> +      expect(typeof scope.global).toBe('object');
add _{ env: { "jasmine": true } }_ to .eslintrc

2017-04-26 10:10 UTC, andela-onnenanya commented on test/frontend/unit/testingAngularUnitSpec.js
> +      expect(typeof scope.global).toBe('object');
Done

2017-04-26 10:31 UTC, emmyakin approved these changes

2017-04-26 10:31 UTC, merged