#143358935 User creates and starts game
andela/mifune-cfh pull request #23
Opened 2017-05-04 21:57 UTC by andela-onnenanya

#### What does this PR do?
Allows user to click on a button to start a game
#### Description of Task to be completed?
Users should be able to create/start a new game
#### How should this be manually tested?
Click on the "Start Game" button close to logout button.
#### Any background context you want to provide?
N/A
#### What are the relevant pivotal tracker stories?
Users should be able to create/start a new game
#### Screenshots (if appropriate)
N/A
#### Questions:
N/A

2017-05-04 23:28 UTC, emmyakin requested changes

2017-05-04 23:28 UTC, andela-eakinyele commented on app/controllers/game.js
> +  // this is just a sample data, should be updated for real user
no need to use dummy data, you can construct the game data fro the request object
e.g 
```
const gameOnwer_id = req.body.gameOwnerId;
and the rest.
```

2017-05-04 23:28 UTC, andela-eakinyele commented on app/controllers/index.js
> +// const mongoose = require('mongoose');
delete the lines rather than comment if we no longer need them

2017-05-04 23:28 UTC, andela-eakinyele commented on app/models/game.js
> +  game_id: String,
maybe we should use camelCase for the schema fields

2017-05-04 23:28 UTC, andela-eakinyele commented on public/js/controllers/index.js
> +          confirmButtonText: 'Yes Am Ready',
Yes / No

2017-05-04 23:28 UTC, andela-eakinyele commented on public/js/controllers/index.js
> +          text: 'You want to start the game now?',
let's use "Start a new Game?"

2017-05-04 23:28 UTC, andela-eakinyele commented on public/js/controllers/index.js
> +            $http.post('/api/games/:id/start').then(
can you move this into the user service, so we don't have to inject $http here

2017-05-05 06:44 UTC, andela-onnenanya commented on public/js/controllers/index.js
> +            $http.post('/api/games/:id/start').then(
Ok, working on all the reviews.

2017-05-05 07:21 UTC, andela-onnenanya commented on public/js/controllers/index.js
> +          text: 'You want to start the game now?',
For line 12 or 13

2017-05-05 12:25 UTC, emmyakin requested changes

2017-05-05 12:25 UTC, andela-eakinyele commented on public/js/controllers/index.js
> +            swal('Cancelled', 'You are off! Shitty you!!!', 'error');
uhm , can you use a proper message like game, cancelled.

And add (error) => {} callback where you check the status code and redirect the user to login page or show a server error message.

2017-05-05 14:22 UTC, emmyakin approved these changes

2017-05-05 16:28 UTC, merged