145190873 UI Cleanup play buttons
andela/mifune-cfh pull request #41
Opened 2017-05-13 18:38 UTC by andela-onnenanya

#### What does this PR do?
Saves played game and retrieves saved games when needed
#### Description of Task to be completed?
UI Cleanup play buttons
#### How should this be manually tested?
Start a new game, play it to the end, once the game ends, you see a modal with game info if the game has been successfully saved.
#### Any background context you want to provide?
N/A
#### What are the relevant pivotal tracker stories?
UI Cleanup play buttons
#### Screenshots (if appropriate)
N/A
#### Questions:
N/A

2017-05-14 09:46 UTC, emmyakin requested changes
Good job, just some comments

2017-05-14 09:46 UTC, andela-eakinyele commented on app/controllers/game.js
> +      throw (err);
do not throw error here, this will hang the request
`res.status(500).send({ error: 'An error occured' });`

2017-05-14 09:46 UTC, andela-eakinyele commented on app/controllers/game.js
> +      res.send(success);
add status code here
res.status(200).json(success)

2017-05-14 09:46 UTC, andela-eakinyele commented on config/routes.js
> +  app.get('/api/games', checkToken, game.retrieveGame);
this endpoint should be 
`/api/users/:id/games`
where id will be the userId

2017-05-14 09:46 UTC, andela-eakinyele commented on public/js/controllers/game.js
> +            function(response) {
arrow function here

2017-05-14 09:46 UTC, andela-eakinyele commented on public/js/controllers/game.js
> +            function(err) {
arrow-function here too

2017-05-14 09:46 UTC, andela-eakinyele commented on public/js/controllers/game.js
> +              console.log('error occured now now')
remove console.log

2017-05-14 09:46 UTC, andela-eakinyele commented on public/js/controllers/game.js
> +/* eslint-disable */
remove eslint-disable, and fix errors

2017-05-14 09:46 UTC, andela-eakinyele commented on app/controllers/game.js
> +  const { gameOwnerEmail } = req.query;
use the gameOwnerId for the search, id will will be in req.params

2017-05-14 09:46 UTC, andela-eakinyele commented on app/controllers/game.js
> +  newGame.gameOwnerEmail = req.body.gameOwnerEmail;
use gameOwnerId

2017-05-14 09:46 UTC, andela-eakinyele commented on app/controllers/game.js
> +      res.send('error ocured');
always use status code and res.json({ error: 'An error occured' })

2017-05-14 09:46 UTC, andela-eakinyele commented on public/js/services/user.js
> +      retrieveGame: () => $http.get('/api/games')
see endpoint url above

2017-05-14 18:34 UTC, andela-onnenanya commented on config/routes.js
> +  app.get('/api/games', checkToken, game.retrieveGame);
Can I use gameOnwerId for clarity purpose?

2017-05-15 14:08 UTC, emmyakin approved these changes
good job

2017-05-15 14:08 UTC, merged