#143358923 convert grunt to gulp task runner
andela/mifune-cfh pull request #5
Opened 2017-04-11 12:03 UTC by andela-cuchendu

#### What does this PR do?
Changes the application task runner from Grunt to Gulp

#### Description of Task to be completed?
Grunt is focused around configuring of the task and plugin using a JavaScript object. Gulp.js, on the other hand, uses an intuitive streaming syntax similar to how Node.JS works and JavaScript Promises.

#### How should this be manually tested?
run `gulp` from the command

#### Any background context you want to provide?
Gulp is more straight forward than grunt, hence the migration

#### What are the relevant pivotal tracker stories?
143358923

#### Screenshots (if appropriate)
N/A

#### Questions:
N/A

2017-04-11 12:54 UTC, emmyakin requested changes
Check Opening PR -
 https://docs.google.com/document/d/1qdSnsKicgoVW0gTVW_ya7MQxRCnbDHeSHRchyUUgFg0/edit

remember to update package.json with npm modules used in gulpfile
See observations

you can ignore hound issues for now.

2017-04-11 12:54 UTC, andela-eakinyele commented on .env
> +MONGOHQ_URL=mongodb://localhost/27017/
this file should not be committed

2017-04-11 12:54 UTC, andela-eakinyele commented on gruntfile.js
> +require('dotenv').config();
I think you can delete this file

2017-04-11 12:54 UTC, andela-eakinyele commented on gulpfile.js
> +        proxy: "http://localhost:6000",
use single quotes, and use process.env.PORT, no hardcoding

2017-04-11 12:54 UTC, andela-eakinyele commented on package.json
>      "grunt-concurrent": "~0.4.0",
remove unused modules, e.g all reference to grunt

2017-04-11 12:54 UTC, andela-eakinyele commented on gulpfile.js
> +        .pipe(gulp.dest('./public/lib/'));
add a .bowerrc file to the root dir, and remove line

2017-04-11 12:54 UTC, andela-eakinyele commented on gulpfile.js
> +    'gruntfile.js',
no need to lint gruntfile
if you are watching this, _'public/js/**/*.js'_, no need to watch _'public/js/*.js'_

2017-04-11 12:54 UTC, andela-eakinyele commented on gulpfile.js
> +    gulp.watch('public/css/*.css');
no task passed to watch

2017-04-11 12:54 UTC, andela-eakinyele commented on config/env/all.js
>  var path = require('path'),
you might as well rewrite this file in es6 syntax, change var to const....

2017-04-11 13:11 UTC, andela-cuchendu commented on .env
> +MONGOHQ_URL=mongodb://localhost/27017/
.env file?

2017-04-11 13:12 UTC, andela-cuchendu commented on gruntfile.js
> +require('dotenv').config();
I should delete .env file?

2017-04-11 15:55 UTC, andela-cuchendu commented on gruntfile.js
> +require('dotenv').config();
Done

2017-04-12 19:09 UTC, andela-eakinyele commented on package.json
> +    "gulp-jshint": "^2.0.4",
remember to clean up jshint on next task

2017-04-12 19:12 UTC, andela-eakinyele commented on .eslintrc
> +    "ecmaFeatures": {
hmm, not sure this is the rule we need

2017-04-12 19:14 UTC, emmyakin approved these changes
Going to merge this for now

2017-04-12 19:14 UTC, merged