#143358917 Configure TravisCI
andela/mifune-cfh pull request #7
Opened 2017-04-11 13:15 UTC by andela-onnenanya

#### What does this PR do?
Integrate TravisCI with readme badge
#### Description of Task to be completed?
Integrate TravisCI with readme badge
#### How should this be manually tested?
Push a commit to a repository
#### Any background context you want to provide?
N/A
#### What are the relevant pivotal tracker stories?
Integrate TravisCI with readme badge
#### Screenshots (if appropriate)
N/A
#### Questions:
N/A

2017-04-11 13:53 UTC, emmyakin requested changes
Check that travisCi runs after making the changes, grab the badge, and add to the readme

2017-04-11 13:53 UTC, andela-eakinyele commented on .travis.yml
> +  - 0.12
can you bump this node version up to whatever version we are using, and update the readme

2017-04-11 13:53 UTC, andela-eakinyele commented on .travis.yml
> +script: gulp
you can omit this, defaults to gulp test, or use gulp test

2017-04-11 13:53 UTC, andela-eakinyele commented on .travis.yml
> +branches:
we would need to run travis on all branches. remove this

2017-04-12 19:42 UTC, emmyakin requested changes
I am not sure the rebase off develop worked, you still have README.md changes

2017-04-12 19:42 UTC, andela-eakinyele commented on .travis.yml
> +install: true
remove this too

2017-04-13 09:15 UTC, andela-onnenanya commented on .travis.yml
> +install: true
Pls, do you mean I should just have lines 1 and 2?

2017-04-13 09:17 UTC, andela-onnenanya commented on .travis.yml
> +install: true
Also, for the rebase, can I reclone the project and do a fresh stuff?

2017-04-13 09:19 UTC, andela-eakinyele commented on .travis.yml
> +install: true
I meant remove install: true, that setting means travis should not install node_modules
I suggest reading this - https://docs.travis-ci.com/user/customizing-the-build

2017-04-18 11:42 UTC, emmyakin approved these changes
All done. Thanks

2017-04-18 12:23 UTC, merged